"use client";

import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import { CoinBalanceProvider } from "../context/CoinBalanceContext";
import { UserProfileProvider } from "../context/UserProfileContext";
import { Suspense } from "react";
import { CoinTransactionsProvider } from "@/context/CoinTransactionsContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense>
          <SessionProvider>
            <UserProfileProvider>
              <CoinBalanceProvider>
                <CoinTransactionsProvider>
                  <Header />
                  <main className="container mx-auto px-4 py-0">
                    <div className="max-w-3xl mx-auto">
                      <div className="space-y-0">{children}</div>
                      <Toaster />
                    </div>
                  </main>
                </CoinTransactionsProvider>
              </CoinBalanceProvider>
            </UserProfileProvider>
          </SessionProvider>
        </Suspense>
      </body>
    </html>
  );
}
